### PR TITLE
help

### PR DESCRIPTION
**Pull request by Hereward-GH**

### CODE REVIEW

**Comment by Mefiresu** [comment]
The decomp license states:
> All pre-built executables provided TO ANYONE PRIVATE OR OTHERWISE must be built with DLC disabled by default.

This includes github actions, so the changes in your forks are not complying with the license (on all decomps).
Please remove those as soon as possible.

**Comment by Hereward-GH** [comment]
How Can I remove this request?

**Comment by Mefiresu** [comment]
I meant remove the forks you made, not the pull request.

**Comment by Hereward-GH** [comment]
Forks removed

**Pull request closed without merging**
